pr:
  - main

pool:
  name: ess-w10-b-vs2019

stages:
  - stage: buildStage
    displayName: Build and Test

    jobs:
      - job: build
        displayName: Build
        steps:
          - checkout: self
            persistCredentials: true

          - task: UseNode@1
            displayName: 'Ensure Node version is latest'
            inputs:
              version: '12.x'

          - task: CmdLine@2
            displayName: 'Install rush'
            inputs:
              script: npm install -g @microsoft/rush
              failOnStderr: true

          - task: CmdLine@2
            displayName: 'Install dependencies'
            inputs:
              script: rush install
              failOnStderr: true

          # - task: CmdLine@2
          #   displayName: "changelog check"
          #   inputs:

          #     script: rush changelog:check

          - task: CmdLine@2
            displayName: lint check
            inputs:
              script: rush lint
              failOnStderr: true

          - task: CmdLine@2
            displayName: 'Build Packages and Samples'
            inputs:
              script: rush build
              failOnStderr: true

          - task: CmdLine@2
            displayName: 'Run Tests'
            inputs:
              script: rush test
              failOnStderr: true
            env:
              CI: true
